### ISSUE TITLE
Add Cloudflare R2

### ISSUE THREAD

**Issue by Brugman** [deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks#27]
I just tried to hack support for Cloudflare R2 into the plugin, similar to Wasabi, and it worked*!

The modifications can be found [here](https://github.com/Brugman/wp-amazon-s3-and-cloudfront-tweaks/commit/9af66e213584a57114bf4116234f919e5af99876).

I know this is a bigger ask than I'm making it sound, but could you run with this and add it to the "tweaks" officially?

My error log was surprisingly only showing one constantly repeating error:
```
[22-Jan-2023 22:34:44 UTC] AS3CF: Could not get Block All Public Access status: Error executing "GetPublicAccessBlock" on "https://MY_ACCOUNT_ID.r2.cloudflarestorage.com/MY_BUCKET_NAME?publicAccessBlock"; AWS HTTP error: Server error: `GET https://MY_ACCOUNT_ID.r2.cloudflarestorage.com/MY_BUCKET_NAME?publicAccessBlock` resulted in a `501 Not Implemented` response:
<?xml version="1.0" encoding="UTF-8"?><Error><Code>NotImplemented</Code><Message>GetPublicAccessBlock not implemented</M (truncated...)
 NotImplemented (server): GetPublicAccessBlock not implemented - <?xml version="1.0" encoding="UTF-8"?><Error><Code>NotImplemented</Code><Message>GetPublicAccessBlock not implemented</Message></Error>
```

**Comment by Brugman** [comment]
👋 @ianmjones

**Comment by Brugman** [comment]
👋 @kevinwhoffman

**Comment by kevinwhoffman** [comment]
@Brugman I appreciate your patience as we've missed some notifications on this repo.

We'd like to integrate Cloudflare R2 into our plugin as it is a popular request, however R2 does not currently handle private objects in a way that is compatible with WP Offload Media. As such, we cannot support using R2 without limiting the functionality of WP Offload Media for R2 users by removing a feature that is needed for secure delivery of downloadable product files and other media that should not be publicly accessible.

We've communicated these limitations to Cloudflare, and we're keeping an eye on the development of R2. We hope to support it in the future should it become more compatible.

In the meantime, I've asked @ianmjones to take a quick look at the code you shared.

**Comment by ianmjones** [comment]
Hey @Brugman, thanks for sharing your code, very interesting.

As @kevinwhoffman mentioned, there are currently issues with Cloudflare's R2 offering that make things difficult for us to support it without making some significant changes to WP Offload Media, or reducing the functionality that can be used when using R2.

However, that doesn't mean we couldn't try out the basic functionality of R2 via this tweaks plugin if someone were to submit a suitable PR. :wink: 

I took a very quick look at your code and noted that there's a few things that would prevent us from accepting it as a PR, some you're probably already aware of because your changes are targetted for your use rather than a PR, but I'll mention everything anyway:

- The `add_filter()` lines would need to be commented out.
- The new functions would need to be in their own little section rather than mixed in with the MinIO examples.
- The functions would need PHP Doc blocks.
- The `REPLACE_WITH_*` placeholders would ideally be replaced with something like a function call that grabs the data from a `define` and a wrapping filter so that people don't need to hunt in the plugin for placeholders to replace.

But, the biggest issue is pinpointed by the debug.log errors you're seeing related to Block All Public Access. At present, whether a storage provider supports Block All Public Access, or Object Ownership Enforcement, both of which are critical pieces of information, comes from properties on the Storage Provider and Delivery Provider sub classes. These properties are not filtered, and so by basing your examples on AWS S3, which supports BAPA and OOE, for a service that seemingly does not, you're probably going to run into a bunch of issues.

There is probably a way around this though! Instead of using AWS S3 as your base service, try using DigitalOcean Spaces as the base. In WP Offload Media, DO uses the same S3-API under the hood, but effectively disables BAPA and OOE as it does not support them.

To use DigitalOcean Spaces as the base, in the filters you set up at the top, try changing `_aws_s3_` to `_do_spaces_`, that might do the trick.

There are a few other small changes that are made by the DigitalOcean sub class, so you may need to be careful with your testing to ensure that things don't break as a result, and maybe override some things. If you run into any issues, the override class is quite small, but might shed some light: https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/providers/storage/digitalocean-provider.php

**Comment by Brugman** [comment]
Thanks for the replies.

@kevinwhoffman Public files is all I'm currently interested in, so if a release with a limited feature set is an option, that would have my vote.

@ianmjones I didn't know the team had already looked at R2. My code is a joke in comparison to the knowledge and experience your team has with connecting external services. It wasn't meant to be the start of a PR, it doesn't even deserve the lengthy response you wrote.

Although, if you think a basic implementation, that is stable and won't throw errors, based on the DO template, can be made easily, I would love to see you guys release it here on the tweaks repo. My involvement would only slow you down.

**Comment by ianmjones** [comment]
No worries @Brugman, it would definitely be better if we could build support for R2 into the plugin itself, the more I think about the Tweaks plugin workaround, the more problems I see due to the way R2 currently works.

We'll no doubt have another look at supporting R2 in due course.
